### ISSUE TITLE
DSA Progress Tracker

### ISSUE THREAD

**Issue by AswinCG2002** [AswinCG2002/Java-DSA-Solutions#1]
- [X]  Introduction to Programming
     - [X]  Types of languages
     - [X]  Memory management

- [X]  Flow of the program
   - [X]  Flowcharts
   - [X]  Pseudocode

- [X]   Introduction to Java
    - [X]  Input and Output in Java
    - [X]  Conditionals & Loops in Java
         - [X]  if else
         - [X]  loops
         - [X]  Switch statements
     - [X]   Data types
     - [X]  Coding best practices
 
- [ ]  Functions
    - [ ]  Introduction  
    - [ ]  Scoping in Java
    - [ ]  Shadowing
    - [ ]  Variable Length Arguments
    - [ ]  Overloading
 
- [ ] Arrays
     - [ ]  Introduction
     - [ ]  Memory management
     - [ ]  Input and Output
     - [ ]  ArrayList Introduction
     - [ ]  Sorting
        - [ ]   Insertion Sort
        - [ ]  Selection Sort
        - [ ]  Bubble Sort
        - [ ]   Count Sort
        - [ ]  Radix Sort
        - [ ]  Cyclic Sort
     - [ ]  Searching
        - [ ]  Linear Search
        - [ ]  Binary Search
        - [ ]   Modified Binary Search
        - [ ]  Binary Search on 2D Arrays
     - [ ]  Sliding window
     - [ ]  Two Pointer
     - [ ]   Subarray Questions
     - [ ]   Kadane's Algorithm
 - [ ]   Pattern questions
 - [ ] Strings
     - [ ] Introduction
     - [ ] How Strings work
     - [ ] Comparison of methods
     - [ ] Operations in Strings
     - [ ] StringBuilder in java
